import os
import sys
import argparse
try:
    import google.generativeai as genai
except ImportError:
    genai = None

def build_harness_engine(api_key: str, prompt_file: str, task_file: str, failure_log: str) -> str:
    # Read the inputs
    try:
        with open(prompt_file, 'r', encoding='utf-8') as f:
            system_prompt = f.read()
        with open(task_file, 'r', encoding='utf-8') as f:
            task_content = f.read()
        with open(failure_log, 'r', encoding='utf-8') as f:
            failure_content = f.read()
    except FileNotFoundError as e:
        print(f"[ERROR] Could not read file: {e}")
        sys.exit(1)

    print("[Harness-R1 Engine] Initializing Gemini Pro Harness Engineer...")
    if not genai:
        raise ImportError("google.generativeai is not installed")
        
    genai.configure(api_key=api_key)

    user_prompt = f"""
    Here is the Original Task Packet (The Harness):
    ```markdown
    {task_content}
    ```
    
    Here is the Failure Trajectory (Reviewer feedback / Crash logs):
    ```markdown
    {failure_content}
    ```
    
    Please generate the Patched Task Packet.
    """

    print("[Harness-R1 Engine] Analyzing failure trajectory and generating Executable Patch...")
    model = genai.GenerativeModel('gemini-1.5-pro', system_instruction=system_prompt)
    response = model.generate_content(
        user_prompt,
        generation_config=genai.types.GenerationConfig(temperature=0.2)
    )
    
    return response.text

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Harness-R1 Evolutionary Patcher")
    parser.add_argument("--task", required=True, help="Path to original task packet")
    parser.add_argument("--failure", required=True, help="Path to failure trajectory/log")
    parser.add_argument("--prompt", required=True, help="Path to harness-engineer-prompt.md")
    parser.add_argument("--output", required=True, help="Path to save the patched task packet")
    
    args = parser.parse_args()
    
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("[ERROR] GEMINI_API_KEY environment variable not set. Please set it to run the real engine.")
        # Fallback for demo purposes if API key is not present
        print("[Harness-R1 Engine] Mocking output for demo since API key is missing...")
        patched_content = "# Patched Task Packet\n\n[MOCKED: This would be generated by Gemini API if GEMINI_API_KEY was set]\n\n"
        with open(args.task, 'r', encoding='utf-8') as f:
            patched_content += f.read().replace("Constraints:", "Constraints:\n- [NEW HARNESS PATCH] DO NOT touch unrelated files!\n- [NEW HARNESS PATCH] Ensure strict type checking!")
    else:
        patched_content = build_harness_engine(api_key, args.prompt, args.task, args.failure)
        
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(patched_content.strip())
        
    print(f"\n[SUCCESS] Patched Harness successfully written to: {args.output}")
